export const SELECT_ARTIST = "SELECT_ARTIST";
export const SELECT_ALBUM = "SELECT_ALBUM";
export const SELECT_SONG = "SELECT_SONG";
export const SELECT_PROFILE = "SELECT_PROFILE";
export const SELECT_PLAYLIST = "SELECT_PLAYLIST";